rsksmart/lumino-light-client-sdk

- src/index.js
- src/store/actions/index.js
- src/store/actions/onboarding.js
- src/store/actions/types.js
- src/store/index.js
- src/store/reducers/clientReducer.js
- src/store/reducers/index.js
- src/utils/messageManager.js
This PR includes the feature for the onboarding of a LC in the SDK.
With this, the a new method has been added to the SDK, which allows it to handle automatically the onboarding of a LC.
The SDK will invoke the hub, get the parameters, sign, send them back, retrieve and store the api key from it.
The SDK will make the api key the default when lumino is initialized.
Also there are methods for overriding the apiKey and retrieve it, in case of need for storage in another environment or testing.
> Onboarding of light client

- src/scripts/close.js
- src/scripts/deposit.js
- src/store/actions/onboarding.js
- src/store/actions/payment.js
- src/store/actions/types.js
- src/store/functions/channels.js
- src/store/functions/index.js
- src/store/reducers/channelReducer.js
- src/store/reducers/channelStatesReducer.js
- src/store/sagas/index.js
- src/utils/messageManager.js
- src/utils/pack.js
- src/utils/validators.js
PR includes #24 so please merge it before this one.
The SDK didn't have multi-token support, we always assumed that channels were unique.
Now we store channels as a key composed of channelId-TokenAddress.
Most of the logic is the same as before, but this comes at a price, previous channels are now incompatible with this format, so this PR is a breaking change.
Now thanks to this the SDK can manage multiple tokens and multiple channels across them, with their balances not being overwritten.
EDIT: 
I've just added to the PR a change to the gasPrice and gasLimit, now for all operations we use the gp and gl passed by the user OR we use the one that we have for default in the config (gasPrice 0.1 gwei and limit 200k wei)
Also there is now an if clause on onboarding, to prevent the sdk for …
> Multi token support and QoL changes

- src/store/actions/open.js
- src/store/actions/tokens.js
This PR has a fix for the openChannel method.
When we tried to store tokens in our storage for future use (in order not to query the HUB all the time whenever we needed one), we stored them and asked the storage for them.
But in this process a bug was introduced and the request was never made, in case that the token wasn't in the storage, all the open channel process would fail due to the request never firing.
With these changes, the open channel method works again.
> Fix Open Channel Token Request

- src/store/actions/open.js
- src/store/functions/tokens.js
- src/store/sagas/index.js
This PR adds a function to the SDK that allows the openChannel script to get and store the token name and symbol.
This is a enhancement that improves the experience of the user, so now they can display the name of the token without any problem.
This PR also deletes some dead and not used code in the saga workers.
> Store token name and symbol on channel

- README.md
This PR is only for the docs.
This is just a typo fix in a param in the docs, which was incorrectly written.
> Fix key name

- src/scripts/close.js
- src/scripts/deposit.js
- src/scripts/open.js
- src/store/actions/close.js
- src/store/actions/notifier.js
- src/store/actions/open.js
- src/store/actions/payment.js
- src/store/functions/channels.js
- src/store/functions/payments.js
- src/store/reducers/paymentsReducer.js
- src/store/sagas/index.js
- src/utils/callbacks.js
- src/utils/messageManager.js
- src/utils/pack.js
- src/utils/validators.js
This PR requires #40 to be merged first.
This PR includes changes to the close channel script, so it can now generate the needed hashes for the on-chain transaction of close channel.
- Now a channel can be closed with balance
- The last balance proof from a partner is used to compose the necessary values
- No changes were made from the user side to the required params.
- Some variables were renamed to be more concise with their origin
- A callback for the close channel completion was added.
> Close channel with balance

- README.md
When we were testing we discovered the next:
The parameter in the close channel function that is named **channelId** is actually used internally as **channel_identifier** therefore, the SDK can not perform a close channel correctly.
This PR aims to fix that documentation issue.
> Fix close channel parameter in readme

- README.md
- package.json
The readme had all the imports using the package without the rsksmart scope, I have modified them to reflect the correct imports.
As well as changing the prepublishOnly hook to prepare, since the dist folder will not be included
See https://github.com/npm/npm/issues/15147
The version of the package was bumped to 0.0.3, to match the Lumino Node release version.
> Fix prepublishOnly hook, add @rsksmart scope to readme imports, bump version

- package-lock.json
- src/Lumino/index.js
- src/store/actions/polling.js
- src/store/index.js
- test/lumino/index.test.js
This was an issue when I was testing reinitalizing the SDK.
For some reason, the memory references of the SDK were properly disposed, but the dispatches action to stop the observables were not working and the pollings continued on the background.
- Fixes the eternal background polling behaviour
- Abstracts a little bit of logic
- The package.lock.json was outdated, this includes an update on it.
> Fix Stop polling on SDK instance destruction

- src/store/actions/onboarding.js
- test/store/actions/onboarding.test.js
This PR aims to fix a behaviour of storing only one API Key.
If we store the API key and change the hub that we use, the api key is stale and will be used in all operations.
When we want to perform and onboarding, the api key will be sent, and the hub will reject our request (due to the invalid api key)
With this PR now the api key is removed from the request before it is sent.
The test for the onboarding was fixed due to an extra measure, stop the polling (in order to prevent stalled requests)
> RLP-723 Do not send API key on onboarding

- __mocks__/axios.js
- src/store/actions/notifier.js
- src/store/actions/open.js
- src/store/reducers/channelReducer.js
- src/utils/callbacks.js
- src/utils/timeoutValues.js
- test/store/actions/open.test.js
Because of some issues with the timing when a hub opens a channel and the LC inmediately requests a deposit, we changed the approach that we consider when a channel is properly opened.
- We take in account the notifiers as before
- But we also require the hub to have answered
- The requests may not take more than 5 minutes in regtest, or 30 in mainnet/testnet
- If they take more than that, the request will be canceled, and a callback will be fired
> RLP-718 Open channel only when hub has answered

- package-lock.json
- src/store/actions/notifier.js
- src/store/actions/open.js
- src/store/reducers/channelReducer.js
- src/store/sagas/index.js
- test/store/actions/open.test.js
In our architecture, we use the notifiers as a means to ensure that a channel was properly opened.
But the notifiers were opening the channels in spite of the checks that we placed.
There was a typo in a number of the notifiers values, that made that behaviour happen.
- The typo was fixed
- Some logic was reused (since the open channel votes may or may not open the channel, as well as the Open channel from the hub request)
- A test was fixed
> Bugfix/rifex 166 - Fix issues when notifiers open a channel

- src/store/actions/deposit.js
- src/utils/callbacks.js
- test/store/actions/deposit.test.js
Due to behaviour differences and user experience, deposits should be done accumulatively, instead of trying to set X value.
Due to this now we set the deposit as offChainBalance + newAmount.
- If the new amount to be the total deposit is equal or lower than the total deposit, it will fail
- In case of the aforementioned failure,an specific callback was designed
- In other cases it will pass as usual
- The deposit tests were missing, I added them
- The case of the insufficient deposit was added to the tests as well
- We have a 100% coverage in the deposit file now.
> RIFEX-177 Make deposit accumulative

- src/store/reducers/channelReducer.js
When making RIFEX-179 a mutation was left in the redux reducer.
It is not very harmful per se, but we really want to avoid them, so we don't have issues with stalled data.
> Fix mutation on redux action RIFEX-179

- src/store/sagas/index.js
This one is my bad, I added code to trigger the open channel callback when the action is dispatched.
But this could happen, even if the channel was not opened (ex. notifiers not responding)
This fixes the issue by deleting such code.
> Bugfix/rifex 195 - Remove improper trigger of open channel

- src/store/actions/deposit.js
This fixes a bug after solving the issue with making incremental deposits.
The issue was that the signed TX had the old amount (the one passed by the user) and not the final amount (the proper new amount which was the incremental one)
This pr fixes the txParams so the signed tx is correct.
> RLP-735 Fix second and onwards deposit on channel

- src/store/actions/payment.js
- src/utils/validators.js
This issue was due to a mistake in the usage of the channelState reducer (which I believe should be deprecated.
The error was
"err The Received Locked Transfer specified a channel with the partner: undefined, which is closed or does not exist"
Which happens when checking that the channel exists and is opened, the reducer didn't have that info, but the channel reducer did.
Changing how the validations receives the data (now it receives the channel) should suffice.
> RLP-736 Fix LT validation with channel opened from partner

- src/store/reducers/notifierReducer.js
This issue was making us losing topics when we switched accounts or changed our wallet address.
This was due to the concept that if a notifier is subscribed to, it should have no topics.
I added a check logic, so instead of overwriting an existing notifier with it topics for an empty object of topics, it should merge it instead.
This should fix any issue when re-subscribing to a notifier and losing all the stored topics on it.
Should solve RIFEX-238 integration
> RIFEX-238 Fix missing topics on wallet reload/changed address

- src/store/actions/notifier.js
- test/store/actions/payment.test.js
- test/utils/validators.test.js
This PR aims to solve RLP-741.
Due to bad programming, the response of the close channel request for new topics on the notifier, was made successfully, but the data was not properly passed, so the function that processed the topics was getting and undefined value.
Also, from previous PRs, a couple of tests were failing, so I fixed them so they would pass again.
- Fixed failing tests
- Pass the proper response data in the processing chain of the notifier actions
> RLP-741 Fix closeChannel notifier response processing and failing tests

- src/config/messagesConstants.js
- test/sign/index.test.js
The non closing BP test was commented since the test in the node was not working properly.
As such, the code was fragile, and our checks were not enough to prevent bugs (such as an invalid recover)
The padding in the message packing before the signature was incorrect, so I corrected it and made sure that the test value was the proper ones.
- Now the test completely passes
- The Non Closing BP method should be working and don't cause any more issues
> RIFEX-254 Fix non closing BP signature method and test

- src/store/functions/payments.js
- src/store/reducers/paymentsReducer.js
- src/utils/messageManager.js
When mediated payments that had a refund generated a LE, the SDK was not properly handling these cases.
- The logic was fixed to accomodate the re-fail of the payment
- The transition is now ok
- The LE messages are managed properly
> RLP-724 Lock Expired Fixes

- src/store/actions/open.js
- test/store/actions/open.test.js
This pr aims to add an extra check when opening a channel, preventing the user from trying to open a channel with themselves.
- The check was added
- Some code was moved so it can use the callback
- A test was added for this behaviour
> RIFEX-282 Do not open channels with yourself

- src/Lumino/index.js
- src/store/actions/close.js
- src/store/reducers/channelReducer.js
- test/store/actions/close.test.js
This PR allows the SDK to work without notifiers
Features 📚
- Notifiers usage is now opt-in
- A new boolean in the config params is required to enable them
- If a channel is open/closed and notifiers usage is disabled, they will immediately transition to the appropiate state
- This means that they need no votes in order to be considered opened/closed
Note ❗️
- If notifiers are not registered, the SDK can not properly transition a channel when a partner creates it or closes it
Solves RLP-806
> RLP-806 Allow the SDK to work without notifiers

- src/store/actions/settle.js
This PR aims to include a missing case for the settlement callback
New features 📚
- The callback is triggered when a settlement is successful
- The callback is also triggered when a settlement fails because a channel was already settled
- Some code was simplified to use abstracted functions (getChannelByIdAndToken)
> RLP-831 Trigger settlement callback

- src/store/actions/secret.js
- src/utils/messageManager.js
This PR aims to include a param in the register secret request, so the HUB can mark the task as processed and will not attempt to send the message afterwards.
New features   📚
- Added a new param called internal_msg_identifier in the register secret request
> RLP-820 Pass internal_msg_identifier in register secret

- src/store/actions/unlock.js
- src/utils/messageManager.js
This PR aims to include a param in the unlock request, so the HUB can mark the task as processed and will not attempt to send the message afterwards.
New features   📚
- Added a new param called internal_msg_identifier in the unlock request
> RLP-821 send internal_msg_identifier in unlock request

- src/store/actions/onboarding.js
- src/store/epics/services.js
This PR provides a solution for issue [RLP-774](https://jirainfuy.atlassian.net/browse/RLP-774), which is about generalizing LC onboarding calls to be transport-agnostic, with the goal of eventually adding a RIF Comms implementation.
This PR is also the counterpart to the changes applied in the Lumino repo—see the original PR [here](https://github.com/rsksmart/lumino/pull/140).
- LC onboarding data request and LC registration request now share an endpoint—the former uses `HTTP GET`, while the latter uses `HTTP POST`.
- LC registration request now submits all its fields inside a generic dictionary object. This is done so that arbitrary fields can be sent, which paves the way for a RIF Comms LC onboarding implementation that uses the same endpoint.
- LC messages endpoint name is slightly …
> RLP-774: generalize LC onboarding

- src/store/actions/onboarding.js
- test/store/actions/onboarding.test.js
This PR implements the onborading for rif comms. It must be merged with hhttps://github.com/rsksmart/lumino/pull/174
The onboarding is in two steps:
1. get hub data
2. register
- now we get the `transport_mode` from the hub data (step 1)
- according to that, we construct the registration body accordingly to each transport implementation
- onboarding for new light client for matrix works
- same for rif comms
- onboarding for an already registered client works for both transports
> Feature/rlp 859/rif comms onboarding impl
